### ISSUE TITLE
Publish typescript types?

### ISSUE THREAD

**Issue by Nokel81** [snovakovic/js-flock#94]
Hello, would it be possible to export `*.d.ts` files for this package?

**Comment by snovakovic** [comment]
@Nokel81 I thought of that and something I wanted to do... to convert this project to TS... and have proper typescript files... I even started doing some progress on that few months back.... But the thing is I just don't have time for that currently and it's not on my list of priorities... So unfortunately don't think that will be happening any time soon.... I still want to do it but don't know when or will I do it... 

Due to above reasons I will close above issue... that saying I'm always open for PR's if there is someone willing to tackle this.
